# Generated by Django 4.1.3 on 2022-11-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('bid', models.IntegerField()),
                ('bname', models.CharField(max_length=77)),
            ],
        ),
    ]
